An extended user-part of the docs for the newly introduced --range-key option
bakdata/quick pull request #141
Opened 2022-11-08 15:08 UTC by DawidNiezgodka

2022-11-09 07:05 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +with the `-range-key` option in the next step.
```suggestion
with the `--range-key` option in the next step.  
```

2022-11-09 07:05 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +has been removed, and `timestamp` has been added.
The schemas look the same. Should they actually change?

2022-11-09 08:21 UTC, torbsto reviewed
Maybe we could try to find a less negative wording :sweat_smile: Instead of seeing the original approach as a limitation, it is the baseline and the `--range-key` argument is a feature for more complex use cases.

2022-11-10 09:10 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +has been removed, and `timestamp` has been added.
Do you mean the `Purchase` type? 
They are not the same. In the [gateway part](https://bakdata.github.io/quick/0.8/user/getting-started/working-with-quick/gateway/) of the docs, the `Purchase` is:
```
type Purchase {
    purchaseId: String!
    productId: Int!
    userId: Int!
    amount: Int
    price: Price
}
```
and here:
```
type Purchase {
    productId: Int!
    userId: Int!
    amount: Int
    price: Price
    timestamp: Int
}
```
The `timestamp` has been added and the `purchaseId` is removed

2022-11-10 09:15 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +          "key": "abc",
To implicitly show that contrary to "normal" range queries (w/o `--range-key`), there is no need to format data so that the message's key must appear as a field in the value.

2022-11-14 09:21 UTC, torbsto requested changes

2022-11-14 09:21 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +    i.e., the topic's key.
[Try to avoid i.e.](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/ie)
```suggestion
    that is, the topic's key.
```

2022-11-14 09:21 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +    follows this schema. The key of each message
```suggestion
    follows this schema. 
    The key of each message
```

2022-11-14 09:21 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +The new value of `keyArgument` - `id` - refers
```suggestion
The new value of `keyArgument` - `userId` - refers
```

2022-11-14 10:20 UTC, torbsto approved these changes

2022-11-14 10:23 UTC, merged