Changes that solve #15
bakdata/quick pull request #16
Opened 2022-05-03 10:01 UTC by DawidNiezgodka

Changes made on this branch resolve the issue #15 i.e. when a user tries to create a gateway, an app, or a mirror with a name that already exists, an exception is thrown in order to show that it is not permitted to create these entities with the same name.

The problem has been solved by extending the deploy function in the KubernetesManagerClient class.
Test classes for ApplicationService, MirrorService and GatewayService have been extended.

2022-05-03 11:08 UTC, raminqaf commented
@DawidNiezgodka Could you please edit the title? Suggestion would be "Fix no error message when creating the same Quick resources multiple times"

2022-05-03 11:16 UTC, torbsto requested changes

2022-05-03 11:16 UTC, torbsto commented on manager/src/test/java/com/bakdata/quick/manager/application/KubernetesApplicationServiceTest.java
> +        assertThat(invalidDeployment).isNotNull();
Please also check the type of the exception and at least the start of the message, so that we can be sure the correct exception is thrown

2022-05-03 11:16 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/gateway/KubernetesGatewayService.java
> +
Unnecessary empty line

2022-05-03 11:16 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +                        .map(singleResourceMetadata -> singleResourceMetadata.getMetadata().getName())
In case one of the resources doesn't exist, it would be null here. I think therefore we should filter for null values

2022-05-03 11:16 UTC, torbsto commented on manager/src/test/java/com/bakdata/quick/manager/application/KubernetesApplicationServiceTest.java
> +        assertThat(invalidDeployment).isNotNull();
This applies to all added tests

2022-05-03 11:22 UTC, raminqaf requested changes

2022-05-03 11:22 UTC, raminqaf commented on manager/src/main/java/com/bakdata/quick/manager/gateway/KubernetesGatewayService.java
> +
remove newline

2022-05-03 11:22 UTC, raminqaf commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +     * Deploys all the resources passed in provided that they have not already been deployed.
This sentence is not correct. Please rephrase it.

2022-05-03 11:22 UTC, raminqaf commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +            }
I have noticed that we don't have any tests for this logic here and for the class in general. Wouldn't it make sense to write some tests for it?

2022-05-03 11:26 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +            }
The added tests `shouldReject...` cover the logic

2022-05-03 11:57 UTC, raminqaf commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +            }
Oh yes, fair enough we can do it there! :+1:

2022-05-03 13:14 UTC, DawidNiezgodka commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +     * Deploys all the resources passed in provided that they have not already been deployed.
Ok, I think that the original one is ok. The additional info is now in the @return part of the javadoc, i.e. Returns a Completable or throws an exception if specific resources already exist

2022-05-03 14:03 UTC, raminqaf requested changes

2022-05-03 14:03 UTC, raminqaf commented on manager/src/test/java/com/bakdata/quick/manager/gateway/KubernetesGatewayServiceTest.java
> +                .hasMessageContaining("Following resources already exist");
Also noticed that the message contains many technical details for the user...
The user should not really care what resources the gateway has. It should only point to the user that the gateway with this particular name exists. Exactly how the user creates a gateway. So for example the getaway already exists and the users types this:
```
quick gateway create test-gateway
```
The user will get:
```
Following resources already exist: quick-gateway-test-gateway, quick-gateway-test-gateway-config, quick-gateway-test-gateway, quick-gateway-test-gateway, quick-gateway-test-gateway
```
Which is super confusing.
Instead, it should be:
```
Following resource already exists: test-gateway
```

2022-05-04 06:41 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/resource/QuickResources.java
> +    String getResourcesName();
Please add java doc for this

2022-05-04 06:41 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +                String resourcesName = quickResources.getResourcesName();
```suggestion
                final String resourcesName = quickResources.getResourcesName();
```

2022-05-04 06:41 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +                throw new BadArgumentException(String.format("Following resources already exist: %s", resourcesName));
```suggestion
                throw new BadArgumentException(String.format("The resource with name %s exists already", resourcesName));
```

2022-05-04 09:49 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/gateway/resource/GatewayResources.java
> +
remove empty line please

2022-05-04 09:49 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/resource/QuickResources.java
> +     * @return The name that a user has chosen for a specific type of resources (gateway, mirror, app)
```suggestion
     * @return The name that a user has chosen for a specific type of resources
```
Even though it's just a comment, don't assume who implements this interface

2022-05-04 09:49 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/resource/QuickResources.java
> +     * A method for retrieving the name of resources (without prefix).
I'm not the biggest fan of starting a comment with `A/This method/class...` because it doesn't add any information.

```suggestion
     * Retrieves the name of resources (without prefix).
```

2022-05-04 09:49 UTC, torbsto commented on manager/src/main/java/com/bakdata/quick/manager/k8s/KubernetesManagerClient.java
> +     * @return Returns a Completable or throws an exception if specific resources already exist
No need to duplicate `return`:
```suggestion
     * @return The completable or an exception if the specific resources already exist
```

2022-05-04 09:57 UTC, raminqaf requested changes

2022-05-04 09:57 UTC, raminqaf commented on manager/src/test/java/com/bakdata/quick/manager/mirror/KubernetesMirrorServiceTest.java
> +                .hasMessageContaining("The resource with the name test-topic already exists");
```suggestion
            .hasMessage(String.format("The resource with the name %s already exists", TOPIC_NAME));
```

2022-05-04 09:57 UTC, raminqaf commented on manager/src/test/java/com/bakdata/quick/manager/gateway/KubernetesGatewayServiceTest.java
> +                .hasMessageContaining("The resource with the name test-gateway already exists");
```suggestion
            .hasMessage(String.format("The resource with the name %s already exists", GATEWAY_NAME));
```

2022-05-04 09:57 UTC, raminqaf commented on manager/src/test/java/com/bakdata/quick/manager/application/KubernetesApplicationServiceTest.java
> +                .hasMessage("The resource with the name my-app already exists");
```suggestion
                .hasMessage(String.format("The resource with the name %s already exists", APP_NAME));
```

2022-05-04 12:38 UTC, raminqaf approved these changes

2022-05-09 06:58 UTC, torbsto approved these changes

2022-05-09 07:01 UTC, merged