Add example for real-time profiles
bakdata/quick pull request #25
Opened 2022-05-16 11:51 UTC by torbsto

2022-06-23 09:18 UTC, raminqaf requested changes

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +You can find the complete code in [Quick's example repository](https://github.com/bakdata/quick-examples/tree/main/profile-store).
404: Page not found

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +Every time a customer listens to a song, the system emits a listening event containing the ids of album,
```suggestion
Every time a customer listens to a song, the system emits a listening event containing the ids of album,
```

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +- first and the last time a user listened to a song
```suggestion
- the first and last time a user listened to a song
```

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +- charts with user’s most listened albums, artists and tracks.
```suggestion
- charts with user's most listened albums, artists, and tracks.
```

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +you can refer to the [getting started guide](../../getting-started/setup-quick).
```suggestion
We are ready to process and query our data with Quick. To start a running Quick instance, you can refer to the [getting started guide](../../getting-started/setup-quick).
```

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +You find the steps for a complete deployment in the `justfile` in the [example repository](https://github.com/bakdata/quick-examples/tree/main/profile-store/deployment/justfile).
I would also add this section to the car-sharing demo

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +quick context create --host "$QUICK_URL" --key "$QUICK_API_KEY" --context customer-profiles
Like the car-sharing demo I would remove them because they are a bit redundant.

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +quick gateway apply profiles -f schema-user-profile.gql
Add these to a separate shell block.

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +??? "The GraphQL schema (`schema-user-profile.gql`)"
Doesn't this make more sense to have the schema in the Gateway section?

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +## Creating profiles
```suggestion
## Creating user profiles
```

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +or [see reference](../reference/cli-commands.md#quick-app-deploy).
Nice! Would also refer this in the car-sharing demo

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +        queryParameter: ["limit", "walks", "walkLength", "resetProbability"])
The indenting is a bit misleading here.

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +??? "The GraphQL schema (`schema-user-profile.gql`)"
```suggestion
??? "The GraphQL user profile schema (`schema-user-profile.gql`)" 
```

2022-06-23 09:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-customer-profiles.md
> +```graphql
Maybe also put this in a drop-down menu like the user profile schema

2022-06-28 15:25 UTC, mkcode92 commented on docs/docs/user/examples/real-time-monitoring.md
> +Exemplary data are contained in the [simulator subdirectory](https://github.com/bakdata/quick-examples/tree/main/carsharing/simulator).
should work after https://github.com/bakdata/quick-examples/pull/8

2022-06-28 15:26 UTC, mkcode92 commented on docs/docs/user/examples/real-time-customer-profiles.md
> +You can find the complete code in [Quick's example repository](https://github.com/bakdata/quick-examples/tree/main/profile-store).
should work after https://github.com/bakdata/quick-examples/pull/7

2022-06-28 15:31 UTC, mkcode92 commented on docs/docs/user/examples/real-time-customer-profiles.md
> +- charts with user’s most listened albums, artists and tracks.
comma is optional https://www.sussex.ac.uk/informatics/punctuation/comma/listing and consistently left out

2022-06-28 16:00 UTC, mkcode92 commented on docs/docs/user/examples/real-time-customer-profiles.md
> +??? "The GraphQL schema (`schema-user-profile.gql`)"
This would make the schema section a bit obsolete. I'd prefer to keep it like this.

2022-06-29 07:03 UTC, torbsto commented on docs/docs/user/examples/real-time-monitoring.md
> +With this use case, we demonstrate how Quick can be used to process data streams
Could you rewrite this file a little to reduce the usage of "we"? See https://docs.microsoft.com/en-us/style-guide/grammar/person#avoid-plural-first-person-we-us

2022-06-29 08:18 UTC, raminqaf requested changes

2022-06-29 08:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-monitoring.md
> +One could for example build a predictive maintenance service with it.
I don't like this part of the text. I think the user reading this already knows the capabilities of Kafka Streams. I would remove this.

2022-06-29 08:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-monitoring.md
> +Having our topics defined, we start by modeling the data required in the dashboard.
```suggestion
After defining the topics, it is time to model the data required in the dashboard.
```

2022-06-29 08:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-monitoring.md
> +With that, we have a subscription operation called `statusUpdates` that we can use to get live updates of `Status`
As @torbsto pointed out you can consider rephrasing the sentences with we, our.

2022-06-29 08:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-monitoring.md
> +The events have the following schema.
```suggestion
The status events have the following schema.
```

2022-06-29 08:18 UTC, raminqaf commented on docs/docs/user/examples/real-time-monitoring.md
> +```
Still not a big fan of this. I would just refer the user to the (../../getting-started/setup-cli)
It is pretty misleading having the CLI command there.

2022-06-29 09:33 UTC, merged