Introduces routing based on partition-host mapping
bakdata/quick pull request #38
Opened 2022-06-28 09:13 UTC by DawidNiezgodka

This PR introduces routing based on partition mapping, and thus resolves #35.

New / changed things:
1. `PartitionRouter<K>` that implements `Router<K>` - responsible for calling an end-point to fetch info about partition-host mapping and serving requests for a specific key (`getHost(Key k)`),
2. `PartitionFinder` and its implementation `DefaultPartitionFinder` that provides strategy for finding partitions,
3. For correct functioning of the router (key serialization), a specific Serde<K> is needed. Thus we have to provide it from classes that use DefaultMirrorClient. This clashes a little bit with the changes introduces by #36, where in many cases Mirror works only with TypeResolver. Thats why there was a need to create a wrapper over TypeResolver and KeySerde to be able to pass them together: `KeySerdeValResolverWrapper<K, V>`

This is a draft as there are no tests yet.

The logic for dealing with a dynamic addition of replicas a la change listener will be handled in a separate issue.

2022-06-28 12:42 UTC, DawidNiezgodka commented
I'm wondering if the router is not coupled too tight with the mirror. We already have a problem with a test in TopicDataClientTest because the router needs information from an endpoint before any mock values are provided.
```
   public DefaultMirrorClient(final String topicName, final MirrorHost mirrorHost,
                               final HttpClient client, final Serde<K> keySerde, TypeResolver<V> valueResolver) {
        this.client = client;
        this.parser = new MirrorValueParser<>(valueResolver, client.objectMapper());
        final StreamsStateHost streamsStateHost = StreamsStateHost.fromMirrorHost(mirrorHost);
        **this.router = new PartitionRouter<>(client, streamsStateHost, keySerde, topicName);**
        this.knownHosts = this.router.getAllHosts();
    }
```

2022-06-28 12:56 UTC, torbsto reviewed
Could you make sure to set up the code style and inspections in IntelliJ?

2022-06-28 12:56 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +        makeAndProcessRequestForPartitionHostMapping(request);
This (and the consequent methods) is basically an implementation of `DefaultMirrorClient`, isn't it? I'd be great if we could reuse it here, though I'm aware that it might be a bit tricky, because this would create a cyclic dependency right now. 
I think the way to go here is to have `BaseMirrorClient`, which is basically the `DefaultMirrorClient` from before. Additionally, you'd add a `PartitionedMirrorClient` which uses a `PartitionRouter` and the `BaseMirrorClient` to implement the logic of this PR.

2022-06-28 12:57 UTC, torbsto commented
For the merge conflicts, see https://bakdata.github.io/quick/0.6/developer/contributing/#dependent-pull-requests

2022-06-28 12:59 UTC, torbsto commented
> I'm wondering if the router is not coupled too tight with the mirror. We already have a problem with a test in TopicDataClientTest because the router needs information from an endpoint before any mock values are provided.
> 
> ```
>    public DefaultMirrorClient(final String topicName, final MirrorHost mirrorHost,
>                                final HttpClient client, final Serde<K> keySerde, TypeResolver<V> valueResolver) {
>         this.client = client;
>         this.parser = new MirrorValueParser<>(valueResolver, client.objectMapper());
>         final StreamsStateHost streamsStateHost = StreamsStateHost.fromMirrorHost(mirrorHost);
>         **this.router = new PartitionRouter<>(client, streamsStateHost, keySerde, topicName);**
>         this.knownHosts = this.router.getAllHosts();
>     }
> ```

You could use a supplier for providing the `PartitionRouter`

2022-06-28 13:19 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +        this.partitionFinder = MirrorConfig.getDefaultPartitionFinder();
Ok. I also added a new constructor in which you can inject PartitionerFinder.

2022-07-11 05:57 UTC, torbsto requested changes

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRegistryClient.java
> +import lombok.extern.slf4j.Slf4j;
There is still something wrong with your setup, because it reorders the imports in a wrong way

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/BaseMirrorClient.java
> +import org.jetbrains.annotations.Nullable;
Please use `edu.umd.cs.findbugs.annotations.Nullable`

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorClient.java
> +
Those two methods are only required for the base class? If so, I think it's best to split this into two separate interfaces

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
This is potentially somewhat costly. You could avoid unnecessary calculation by wrapping it in an if statement

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/StreamsStateHost.java
> +    public static PartitionFinder getDefaultPartitionFinder() {
Where do you use this? I think this should be handled by dependency injection

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +    private final Map<Integer, MirrorHost> partitionToMirrorHost = new HashMap<>();
move into constructor

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +        for (final Map.Entry<Integer, String> entry : this.partitionToHost.entrySet()) {
This comes down to personal preference, but I would use the streams API here and return a new Map

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionFinder.java
> +    int getForSerializedKey(final byte[] serializedKey, final int numPartitions);
Could we remove `numPartitions` from the interface? It seems to me that it is an implementation detail of a particular `PartitionFinder` and shouldn't be part of the interface itself. Not too important though if you feel it isn't straightforward to implement

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> + * A router that leverages the fact that a mirror knows which partitions it stores
To be precise, this leverages the fact that a mirror known which partitions which replica stores, not only itself

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> + * (it has a mapping between a partitions and a host),
```suggestion
 * (it has a mapping between partitions and a host),
```

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/util/KeySerdeValResolverWrapper.java
> +@Getter
You can use `@Value` here to save even more boilerplate

2022-07-11 05:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/util/KeySerdeValResolverWrapper.java
> +public class KeySerdeValResolverWrapper<K, V> {
```suggestion
public class KeySerdeValueResolverWrapper<K, V> {
```

2022-07-11 07:02 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/BaseMirrorClient.java
> +import org.jetbrains.annotations.Nullable;
At first I did but then I thought "no, it doesn't seem right", so I check some classes you or Ramin wrote, and the first I found was QuickGraphQLInvocation which has import org.jetbrains.annotations.Nullable; so I thought this one is correct and edu.umd is wrong :P

2022-07-11 09:24 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/StreamsStateHost.java
> +    public static PartitionFinder getDefaultPartitionFinder() {
In `PartitionedMirrorClient` there are two constructors: One with PartitionFinder injected, another without. When no PartitionFinder is passed, then the constructor calls: `this.partitionFinder = StreamsStateHost.getDefaultPartitionFinder();`

2022-07-11 09:33 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionFinder.java
> +    int getForSerializedKey(final byte[] serializedKey, final int numPartitions);
Maybe we can make a separate issue out of it?

2022-07-11 11:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionFinder.java
> +    int getForSerializedKey(final byte[] serializedKey, final int numPartitions);
No need, it's fine for now

2022-07-11 11:32 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorClient.java
> +
Actually there is no duplication: both BaseMirrorClient (BMC) and PartitionedMirrorClient (PMC) use MirrorRequestManager to manage their requests to the mirror. They use functions that are implemented there, i.e. delegate their request so that the logic does not have to be implemented in each of those classes. Previously we had duplication as a big part of the logic for making request was identical in BMC and PMC.

Regardless of this, BMC and DefaultMirrorClient (DMC) are almost identical, i.e. DMC uses BMC to delegate all its reqs so one could argue if the distinction between the two is reasonable now. However, should we change or extend DMC, the use of BMC might turn out fair-minded so I would leave it as it is.

2022-07-11 11:37 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionFinder.java
> +    int getForSerializedKey(final byte[] serializedKey, final int numPartitions);
Ok, so maybe an issue in quick-internal? Just to have in mind that this might be improved in the future.

2022-07-11 11:59 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorClient.java
> +
Exactly, my question was about the relationship of BMC and DMC. In which scenario would the existence of BMC make sense? You've introduced it to avoid duplication in PMC and DMC, though this is now handled by the request manager.

2022-07-11 13:15 UTC, torbsto requested changes

2022-07-11 13:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorClient.java
> + * An abstract BaseMirrorClient that provides basic properties and functionalities for Mirror Clients.
The old comment seems more fitting

2022-07-11 13:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorClient.java
> +    protected final MirrorHost host;
All variables can be private again

2022-07-11 13:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorClient.java
> +        this.mirrorRequestManager = new DefaultMirrorRequestManager(client);
I'd prefer if this would also be injected

2022-07-11 13:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +    protected final HttpClient client;
```suggestion
    private final HttpClient client;
```

2022-07-11 13:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ParserFunction.java
> +public interface ParserFunction<T> {
Does this really have to be public?

2022-07-11 13:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +        log.info("Initializing partition router...");
add some contex: For which topic, which mirror?

2022-07-12 10:52 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
Nope:
```
final String url = this.streamsStateHost.getPartitionToHostUrl();
        Map<Integer, String> partitionHostMappingResponse = new HashMap<>();
        try (final ResponseBody responseBody = requestManager.makeRequest(url)) {
            if (responseBody != null) {
                final TypeReference<Map<Integer, String>> typeRef = new TypeReference<>() {};
                partitionHostMappingResponse = this.client.objectMapper()
                    .readValue(Objects.requireNonNull(responseBody).byteStream(), typeRef);
                log.info("Collected information about the partitions and hosts."
                        + " There are {} partitions and {} distinct hosts", partitionHostMappingResponse.size(),
                    (int) partitionHostMappingResponse.values().stream().distinct().count());
            } else {
                log.info("Response body was null. Returning an empty mapping.");
            }
            return partitionHostMappingResponse;
        } catch (final IOException e) {
            throw new InternalErrorException("There was a problem handling the response: " + e.getMessage());
        }
```

2022-07-12 10:53 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
But probably the empty mapping is senseless, so I think I would rather throw an exception there.

2022-07-12 10:54 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
```
        try (final ResponseBody responseBody = requestManager.makeRequest(url)) {
            if (responseBody != null) {
                final TypeReference<Map<Integer, String>> typeRef = new TypeReference<>() {};
                final Map<Integer, String> partitionHostMappingResponse = this.client.objectMapper()
                    .readValue(Objects.requireNonNull(responseBody).byteStream(), typeRef);
                log.info("Collected information about the partitions and hosts."
                        + " There are {} partitions and {} distinct hosts", partitionHostMappingResponse.size(),
                    (int) partitionHostMappingResponse.values().stream().distinct().count());
                return partitionHostMappingResponse;
            } else {
                throw new InternalErrorException("Response body was null. Returning an empty mapping.");
                
            }
```

2022-07-12 10:57 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
I was referring to ` (int) partitionHostMappingResponse.values().stream().distinct().count()` in the logging statement

2022-07-12 11:06 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
Ok, I thought you were referring to the fact that makeRequest can return null - which I didn't cover btw.
Basically we can throw the info about the number of hosts away if you think it is costly. On the other hand, the number of replicas won't change dynamically (will it?), so I guess you won't compute this very often

2022-07-12 11:12 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    (int) partitionHostMappingResponse.values().stream().distinct().count());
You can wrap it in  `if(log.isInfoEnabled) {...}`.

For the null case: Good catch, though `/partitions` should never return `null`. I'd also suggest exiting early, e.g.:
```java
if (responseBody == null) {
  throw new InternalErrorException(...)
}

// here conversion to map
```

2022-07-12 11:17 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +    private List<MirrorHost> knownHosts;
In order to avoid logic in constructor. The init of the router and the corresponding known hosts happens in the initRouter function where you assign specific values to these two fields.

2022-07-12 11:43 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +        Map<Integer, String> partitionHostMappingResponse = new HashMap<>();
With the early return (an exception) in case of failure we have only one place where it can be initialized so it can be final:

```
private Map<Integer, String> makeRequestForPartitionHostMapping() {
        final String url = this.streamsStateHost.getPartitionToHostUrl();
        try (final ResponseBody responseBody = requestManager.makeRequest(url)) {
            if (responseBody != null) {
                final Map<Integer, String> partitionHostMappingResponse = this.client.objectMapper()
                    .readValue(Objects.requireNonNull(responseBody).byteStream(), MAP_TYPE_REFERENCE);
                if (log.isInfoEnabled()) {
                    log.info("Collected information about the partitions and hosts."
                            + " There are {} partitions and {} distinct hosts", partitionHostMappingResponse.size(),
                        (int) partitionHostMappingResponse.values().stream().distinct().count());
                }
                return partitionHostMappingResponse;
            } else {
                throw new InternalErrorException("Response body was null.");

            }
        } catch (final IOException e) {
            throw new InternalErrorException("There was a problem handling the response: " + e.getMessage());
        }
```

2022-07-12 13:54 UTC, torbsto requested changes

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            final MirrorValue<T> mirrorValue;
Why declare this variable here?

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java
> +     * @param parser parser
please add a proper description

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java
> +     * @param <T>    type
see above; type of what?

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +    private List<MirrorHost> knownHosts;
I don't think this is a good reason. You can either return those two values from the `initRouter` function or drop `initRouter`as it is only 4 lines.

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +
You can also use  `this(...)` here

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +            if (responseBody != null) {
I'd still prefer the early error as written before, see https://github.com/bakdata/quick/pull/38#discussion_r918844318

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +        this.partitionToMirrorHost = convertHostStringToMirrorHost();
```suggestion
        this.partitionToMirrorHost = this.convertHostStringToMirrorHost();
```

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/config/MirrorConfig.java
> +
remove empty line

2022-07-12 13:54 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/directives/rest/RestDirectiveWiringTest.java
>      void setUp() {
Any reason you've reformatted this file? It's make reviewing pretty hard because of the noise

2022-07-12 13:54 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/QueryListArgumentFetcherTest.java
> +import java.util.ArrayList;
wrong import order

2022-07-12 13:54 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/QueryListFetcherTest.java
> +import java.util.List;
wrong import order

2022-07-12 13:54 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/RestDataFetcherTest.java
> +import java.util.HashMap;
see above :)

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +    private final Map<Integer, String> partitionToHost;
Do you need to keep this map around? Seems like you only need it for initializing

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +        if (partitionToMirrorHost.isEmpty() || !partitionToMirrorHost.containsKey(partition)) {
Isn't `isEmpty()` covered by `containsKey(...)`? Whenever it's empty, `containsKey` will also return false

2022-07-12 13:54 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                    .readValue(Objects.requireNonNull(responseBody).byteStream(), MAP_TYPE_REFERENCE);
```suggestion
                    .readValue(responseBody.byteStream(), MAP_TYPE_REFERENCE);
```
You've checked it above

2022-07-12 14:38 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +
There were 3 constructors and only one was used so I removed the unnecessary ones. One can add them later if they are needed

2022-07-12 14:52 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +
And concerning the initRouter(), I still have some doubts. On one hand, this doesnt look good to me:
    ```
public PartitionedMirrorClient(final String topicName, final MirrorHost mirrorHost, final HttpClient client,
                                   final Serde<K> keySerde, final TypeResolver<V> valueResolver,
                                   final PartitionFinder partitionFinder) {
        this.streamsStateHost = StreamsStateHost.fromMirrorHost(mirrorHost);
        this.client = client;
        this.keySerde = keySerde;
        this.topicName = topicName;
        this.partitionFinder = partitionFinder;
        this.parser = new MirrorValueParser<>(valueResolver, client.objectMapper());
        this.requestManager = new DefaultMirrorRequestManager(client);
        log.info("Initializing partition router for the mirror at: {} and the topic: {}.",
            this.streamsStateHost.getHost(), this.topicName);
        final Map<Integer, String> response = makeRequestForPartitionHostMapping();
        this.router = new PartitionRouter<>(this.keySerde, this.topicName, this.partitionFinder, response);
        this.knownHosts = this.router.getAllHosts();
    }
```
On the other hand, create an extra object and passing again all the needed info just to have these two fields seems like an overkill.
The problem with the logic in constructor is: if we want to overload the constructor later, we will have a code duplication. That was the reason to have it in a separate function.

2022-07-12 14:59 UTC, DawidNiezgodka commented on gateway/src/test/java/com/bakdata/quick/gateway/directives/rest/RestDirectiveWiringTest.java
>      void setUp() {
Hmm, I took a look at the file where I changed sth and than just applied checkstyle. Thought it is desired to do so.

2022-07-13 05:10 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/directives/rest/RestDirectiveWiringTest.java
>      void setUp() {
It seems like you hit reformat twice, IntelliJ then reformats custom line breaks. Could you revert the changes?

2022-07-13 05:12 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +
A new class is ~6 lines, that's totally fine for this use case. 

Also regarding the logic in the constructor: That's why `this(...)` is preferred :)

2022-07-15 12:09 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +        final int partition = partitionFinder.getForSerializedKey(serializedKey, this.partitionToMirrorHost.size());
Couple of missing `this`

2022-07-15 12:09 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/StreamsStateHost.java
> +        return host;
this

2022-07-15 12:09 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorValueParser.java
> +public class MirrorValueParser<V> {
I still don't see why this needs to be public now?

2022-07-15 12:09 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/QueryListFetcherTest.java
> +import java.util.List;
not resolved

2022-07-15 12:09 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/RestDataFetcherTest.java
> +import java.util.HashMap;
not resolved

2022-07-15 12:09 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +    public MirrorHost getHost(final K key) {
Maybe `findHost` or `calcualteHost`? I think it can be misleading to use `get...` for a non-trivial task

2022-07-15 13:50 UTC, DawidNiezgodka commented on gateway/src/test/java/com/bakdata/quick/gateway/directives/rest/RestDirectiveWiringTest.java
>      void setUp() {
Ok, I'll just copy it from master.

2022-07-15 13:53 UTC, DawidNiezgodka commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/QueryListArgumentFetcherTest.java
> +import java.util.ArrayList;
I will copy from master

2022-07-15 13:53 UTC, DawidNiezgodka commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/QueryListFetcherTest.java
> +import java.util.List;
same as above

2022-07-15 14:00 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            final Response response = this.client.newCall(request).execute();
When you do this, you will explicitly close the input stream, and you won't be able to read from it in the PartitionedMirrorClient.

2022-07-18 05:17 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            final Response response = this.client.newCall(request).execute();
Ah true, could you add a comment for this?

2022-07-21 13:34 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +            throw new InternalErrorException("There was a problem handling the response: " + e.getMessage());
```suggestion
        } catch (final IOException exception) {
            throw new MirrorException("There was a problem handling the response: ", HttpStatus.INTERNAL_SERVER_ERROR, exception);
```

2022-07-21 13:34 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +                throw new InternalErrorException("Response body was null.");
This is still a MirrorClient. I would do it like the DefaultMirrorClient:
```suggestion
                throw new MirrorException("Response body was null.", HttpStatus.INTERNAL_SERVER_ERROR);
```

2022-07-21 13:34 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +    }
See above

2022-07-21 13:34 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/StreamsStateHost.java
> + * that delivers info about kafka streams app state.
```suggestion
 * that delivers info about Kafka Streams app state.
```

2022-07-21 13:34 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/config/MirrorConfig.java
> +    public static MirrorConfig directAccessToStreamsState() {
Javadocs?

2022-07-21 13:34 UTC, raminqaf commented on common/src/test/java/com/bakdata/quick/common/api/client/routing/PartitionRouterTest.java
> +
remove line

2022-07-21 13:34 UTC, raminqaf commented on common/src/test/java/com/bakdata/quick/common/api/client/routing/PartitionRouterTest.java
> +
remove line

2022-07-22 09:58 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java
> +     * Responsible for making a request to a specific url and processing the result.
Yea, I also didn't like that. That's why it has been changed. The results are in another branch: https://github.com/bakdata/quick/blob/8ed54d4c504a553b6d1c0e841d8651261f9de43e/common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java

2022-07-22 13:14 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java
> +     * @return response body if successful; null if resource has not been found
@torbsto - I asked you the same question, and you said that sometimes it is ok to return null (see Slack, 6.07)

2022-07-22 13:30 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java
> +     * @return response body if successful; null if resource has not been found
Yes, in case the GraphQL query defines the return type as nullable we have to propagate this properly and cannot throw an exception

2022-07-28 06:02 UTC, torbsto approved these changes

2022-07-28 06:57 UTC, raminqaf approved these changes

2022-07-28 07:45 UTC, merged