A mechanism for automatic update of partition mapping info
bakdata/quick pull request #46
Opened 2022-07-15 13:36 UTC by DawidNiezgodka

This PR resolves #39.

2022-07-18 07:12 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +        this.client.okHttpClient().interceptors().add(chain -> {
This will tell the other mirror replica that there was a cache miss, but we want to inform the caller of this mirror about it. So you have to manipulate the response, not the request. See https://docs.micronaut.io/2.5.4/guide/#requestResponse

2022-07-19 08:43 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +        List<V> values = new ArrayList<>();
The previous way is definitely preferable because it uses the reactive runtime underneath and doesn't block on IO. I think you could just modify the final call to `map` to create a `MirrorValue` wrapped in a `HttpResponse`

2022-07-19 08:43 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +    private boolean updateCache = false;
This doesn't work if because it's not thread-safe.

2022-07-19 08:43 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +    private V internalGet(final String rawKey) {
I don't see the advantage of using an `internalGet`, especially with a mutable member variable.
If you want to use the `internalGet`, why not just return the final `HttpReponse<...>`?

2022-07-19 08:43 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +        MirrorValue<List<V>> mirrorValue =
Same as above: Try to use the reactive API

2022-07-19 09:13 UTC, DawidNiezgodka commented
> > In order to account for the fact that we might have a header that encourages us to update the routing info, I introduced a ResponseWrapper that consists of a nullable ResponseBody and Optional that can be filled with if a header is available,
> 
> Have you thought about using the `Response` itself? It seems like the easier choice to me. Am I missing something?

Ye, I was thinking about it and even tried it out but somehow the dealing with nulls seemed more complicated than when you have it in a wrapper class. I can go back to this idea though if it is desired :)

2022-07-19 09:20 UTC, DawidNiezgodka commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +    private V internalGet(final String rawKey) {
I introduced it because `getValues` calls `get` multiple times, and I thought that it would be easier to have a separate function that return just V and not `Single<Http<MirrorValue<V>>>>`. Hmm but yes, we can have multiple HttpResponses from each get, extract all the values, and check if any of Responses had the update-cache-header set.

2022-07-19 09:21 UTC, DawidNiezgodka commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +    private boolean updateCache = false;
Ye, its time to change the way of thinking from a single threaded apps to multi threaded 👯‍♂️

2022-07-19 09:24 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +        log.info("Updating router information");
This was already changed in another branch concerning Router but they have not been rebased yet.

2022-07-19 10:10 UTC, DawidNiezgodka commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +        MirrorValue<List<V>> mirrorValue =
This one is tough .

2022-08-01 06:20 UTC, torbsto requested changes

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/util/QuickConstants.java
> +    private static final String CACHE_UPDATE_MESSAGE = "There was a cache miss. Please update routing information.";
I'd argue that we don't need such a message because this is a technical implementation. I suggest completely removing the message: If the header exists, there was a cache-miss

2022-08-01 06:20 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +
remove

2022-08-01 06:20 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +    void shouldReadHeaderAddUpdateRouter() throws JsonProcessingException {
```suggestion
    void shouldReadHeaderAndUpdateRouter() throws JsonProcessingException {
```

2022-08-01 06:20 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        assertThat(Objects.requireNonNull(topic).getName()).isEqualTo(DEFAULT_TOPIC);
I don't see how this tests if the underlying mapping was actually updated?

2022-08-01 06:20 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/MirrorController.java
> +    public Single<? extends HttpResponse<MirrorValue<V>>> get(@PathVariable("key") final String keyString) {
Any reason you're using a wildcard here but not for other routes?

2022-08-01 06:20 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +            // The cast in the second map function is possible because MutableHttpResponse is of the same type
This comment seems outdated. There is no `map` nor `MutableHttpResponse`

2022-08-01 06:20 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +            .map(listOfResponses -> {
Extract the lambda into its own method please

2022-08-01 06:20 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +            .map(e -> HttpResponse.created(new MirrorValue<>(e)));
Please rename `e` into something less abstract

2022-08-01 06:20 UTC, torbsto commented on mirror/src/test/java/com/bakdata/quick/mirror/MirrorApplicationIntegrationTest.java
> +                .statusCode(201)
Why did this change? 201 seems wrong to me

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/Router.java
> +    void update(Map<Integer, String> updatedRoutingInfo);
```suggestion
    void updateRountingInfo(Map<Integer, String> updatedRoutingInfo);
```

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +        log.info("Updating router information");
Please add context

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +        log.info("Updating router information");
I also think this should be a debug level

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> + * It consists of a response body extracted from the response and an optional field
```suggestion
 * A wrapper for a response from a call to made with the HttpClient.
 
 * <p>
 * It consists of a response body extracted from the response and an optional field
```

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +@Setter
Please use `@Value`

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +    @NonNull
Not needed

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +        final ResponseWrapper responseWrapper = new ResponseWrapper();
As I've noted above, please make this immutable

2022-08-01 06:20 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +                responseWrapper.setResponseBody(null);
This could still be a cache miss

2022-08-03 06:50 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/util/QuickConstants.java
> +    private static final String CACHE_UPDATE_MESSAGE = "There was a cache miss. Please update routing information.";
But isn't a header a key-value pair? 
The `CACHE_UPDATE_MESSAGE` was thought of as a value thereof.
For example, if you have Keep-Alive header, you have `Keep-Alive: 100`. In a similar fashion, I thought that we would have a (custom) header, `X-Cashe-Update: There was a cache miss`.

2022-08-03 06:54 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/util/QuickConstants.java
> +    private static final String CACHE_UPDATE_MESSAGE = "There was a cache miss. Please update routing information.";
The API itself forces you to put a key and a value there, i.e.: `header(CharSequence name, CharSequence value)`. What would you like to put as a value parameter?

2022-08-03 06:56 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/util/QuickConstants.java
> +    private static final String CACHE_UPDATE_MESSAGE = "There was a cache miss. Please update routing information.";
This [StackOverflow question](https://stackoverflow.com/questions/58854683/whats-the-standard-format-for-representing-true-and-false-values-in-an-http-hea) gives a couple of possible options, I'm fine with all of them. My point is just that `There was a cache miss. Please update routing information.` is like a user facing description and isn't needed here

2022-08-03 09:19 UTC, DawidNiezgodka commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        assertThat(Objects.requireNonNull(topic).getName()).isEqualTo(DEFAULT_TOPIC);
1. You start with the following mapping: 1->host, 2->host. This is the mapping the router is initialised with. It is fetched by the first `server.enqueue` in `@BeforeEach`.
2. When you make a call to `this.topicDataClient.fetchValue(),` you'll make a request in `DefaultMirrorRequestManager`. Since we create a mocked response with header, the control statement at the line 71 will be called and a header will be set in the `ResponseWrapper`. Because of this `this.updateRouterInfo();` at 90 of `PartitionedMirrorClient` will be called. Eventually, you will get a new mapping: 1->host, 2->host, 3->host. 
3. Now, in the first call to `this.topicDataClient.fetchValue`, the returned partition is 2. If we made a consecutive call to to `this.topicDataClient.fetchValue`, the returned partition will be 3. Why do we get 2 and then 3? This is a way of functioning of the custom `PartitioningRouter` that was made for the purpose of the test, see `PartitionFinderForUpdateMappingTest`,
 If the info had not been updated, you would have received `IllegalStateException`.
4. But ye, the test is incomplete, because we have to add another `this.topicDataClient.fetchValue` in order to be sure that the exception is not thrown. If you add it, it works.

2022-08-03 09:28 UTC, DawidNiezgodka commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        assertThat(Objects.requireNonNull(topic).getName()).isEqualTo(DEFAULT_TOPIC);
I will add this description to the test, if you say it's ok

2022-08-03 09:32 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        assertThat(Objects.requireNonNull(topic).getName()).isEqualTo(DEFAULT_TOPIC);
I'd change [PartitionFinderForUpdateMappingTest.java](https://github.com/bakdata/quick/pull/46/files/adb9a65cd1e9215b57602dfe8f42e7c84fcad938#diff-c6c4046ffa9bbf20608e4e24453ec8048df27cec992e6ad8a0374ea4852c05ff) to be explicit. Maybe something similar to the `enque` of the MockWebServer for the partition to be returned next.

2022-08-03 12:59 UTC, DawidNiezgodka commented on mirror/src/test/java/com/bakdata/quick/mirror/MirrorApplicationIntegrationTest.java
> +                .statusCode(201)
It no longer works with 200 after we have introduced HttpResponse as a return value. To be honest, I dunno why, but maybe it treats it different that just returning a value.

2022-08-03 13:51 UTC, DawidNiezgodka commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        assertThat(Objects.requireNonNull(topic).getName()).isEqualTo(DEFAULT_TOPIC);
Ok, I changed it but I'm not sure if this is what you meant.

2022-08-04 15:24 UTC, torbsto requested changes

2022-08-04 15:24 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +    @NonNull
Not resolved, see https://github.com/bakdata/quick/pull/46/files#r934171886

2022-08-04 15:24 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +    Optional<String> updateCacheHeader;
What's the benefit of using `Optional<String>` here? Are we ever interested in the value inside the optional? I'd have expected a boolean instead

2022-08-04 15:24 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        assertThat(Objects.requireNonNull(topic).getName()).isEqualTo(DEFAULT_TOPIC);
Let's talk about it synchronously, I had something different in mind :smile:

2022-08-04 15:24 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/testutils/PartitionFinderForUpdateMappingTest.java
> +public class PartitionFinderForUpdateMappingTest implements PartitionFinder {
```suggestion
public class TestPartitionFinder implements PartitionFinder {
```

2022-08-04 15:24 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +     * and not just HttpResponse. However, MutableHttpResponse is of type HttpResponse so there is no clash
> However, MutableHttpResponse is of type HttpResponse so there is no clash with the QueryService interface that uses HttpResponse.

No need to document this, it's pretty intuitive that this is the case

2022-08-04 15:24 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +            return HttpResponse.created(new MirrorValue<>(values)).status(200);
You can extract this as a variable and reuse it above

2022-08-04 15:24 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +            .map(response -> Objects.requireNonNull(response.body()).getValue()).collect(Collectors.toList());
```suggestion
            .map(response -> Objects.requireNonNull(response.body()).getValue())
            .collect(Collectors.toList());
```

2022-08-04 15:24 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/testutils/TestUtils.java
> +    public static PartitionFinder getPartitionFinderForMappingUpdateTest() {
I don't really see the benefit of this method?

2022-08-04 15:24 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/PartitionedMirrorClient.java
> +            if (response != null) {
Can the response even be null now that you use a wrapper?

2022-08-08 14:52 UTC, raminqaf reviewed
looks good to me just some small adjustments

2022-08-08 14:52 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +     * Checks if the X-Cache-Update header has been set.
Could you please add a `@link` tag and point out the X-Cache-Update to the `HeaderConstants` class?

2022-08-08 14:52 UTC, raminqaf commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +     * 3) Because of this, this.updateRouterInfo(); at 90 of PartitionedMirrorClient will be called.
I would remove the line numbers in the comments

2022-08-09 11:24 UTC, torbsto reviewed
This handles the case when a new replica is added. What about a replica being removed?

2022-08-09 11:24 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +public class ResponseWrapper {
I'd create a static creator `fromResponse(Response response)` that includes the corresponding logic for setting the header flag

2022-08-09 11:24 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +     * 1) We start with the following mapping: 1->host, 2->host. This is the mapping the router is initialized with.
Generally, if you need such a long comment to explain a basic test, I'd suggest rather trying to rewrite the test to be more expressive. 
In this case, the problem is just that the relationship between the first router mapping, and the partition of the second call is hard to find. Therefore, my previous suggestion was to add a method `enque` for the `TestPartitionFinder`. It lets you start with `enque(2)` to signal that the first response is routed to the host of partition 2. Then, prior to the second request, you could call `enque(3)` to signal that the next partition returned is 3. 
It would maybe also be helpful to first test that if it's not updated, an error is being thrown.

2022-08-09 18:18 UTC, DawidNiezgodka commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +     * 1) We start with the following mapping: 1->host, 2->host. This is the mapping the router is initialized with.
Ok, but I'm not 100% convinced that it helps to understand the test. Someone might think: _"Ok, there's a partition finder, there is some queue, they enqueue 2, and then 3, but wait, this was supposed to be the test of router not partition finder, etc."._
I think that someone who reads the test must dig deeper to connect the dots. I agree that the comment is wordy, but I intended to help a potential reader find appropriate fragments in the code to facilitate understanding.
I guess that the underlying problem is that the router's logic is concealed. We don't interact with it directly. Instead, we influence its behavior via playing with PartitionFinder. Generally, it is difficult to grasp what happens behind the scenes without analyzing the code in detail.

2022-08-15 06:51 UTC, torbsto requested changes

2022-08-15 06:51 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +        /*
Please us always line comments except for JavaDoc

2022-08-15 06:51 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            /*
Extract all of this into a method

2022-08-15 06:51 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            if (exception instanceof UnknownHostException) {
Did you test this? Is this actually the exception that is thrown in such cases?

2022-08-15 06:51 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +                final String keyInfo = Arrays.stream(url.split("/")).skip(3).collect(Collectors.joining("/"));
You can just use OkHttp's `HttpUrl` class to retrive this. You can get the current one by calling `request.httpUrl()`

2022-08-15 06:51 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +                    fallbackResponse.header(HeaderConstants.getCacheMissHeaderName(),
It feels wrong to me to mutate the original response to propagate this information. I'd create an additional method in `ResponseWrapper` to cover this case.

2022-08-15 06:51 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> + * </p>
```suggestion
 *
```

JavaDoc is weird, there is actually no need to close the tags

2022-08-15 09:25 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            if (exception instanceof UnknownHostException) {
If you run the following test: `PartitionedMirrorClientTest.shouldReadHeaderAndUpdateRouterWithFewerReplicas`, you will eventually hit this `if` statement. With the host:` http://localhost:1234/mirror/dummy`, which points nowhere, you receive: `java.net.UnknownHostException: local: nodename nor servname provided, or not known`.

2022-08-15 09:40 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +                    fallbackResponse.header(HeaderConstants.getCacheMissHeaderName(),
Wait, but you're not changing the value of any variable here. There is a new request and a new response. Where can you see a mutation of the original response here?

2022-08-15 09:45 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +                    fallbackResponse.header(HeaderConstants.getCacheMissHeaderName(),
The method itself can be put into ResponseWrapper.

2022-08-15 13:14 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +                    fallbackResponse.header(HeaderConstants.getCacheMissHeaderName(),
Sorry, not the original but fallback response

2022-08-15 13:16 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +            if (exception instanceof UnknownHostException) {
I'm not sure if 1) this is also the case in a cluster and 2) we want to rely on it. I think it's fine to use it for every IOException. Eventually, we can look into more nuanced recovery strategies.

2022-08-16 10:08 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +import org.jetbrains.annotations.NotNull;
No need for `@NotNull`

2022-08-16 10:08 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +    // This code covers a situation where a replica is removed, and we can no longer
JavaDoc for methods

2022-08-16 10:08 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +    private ResponseWrapper getResponseFromFallbackService(final String url, final Request request) {
Why is this part of `DefaultMirrorRequestManager`? Isn't that only relevant for the `PartitionedMirrorClient`?

2022-08-16 10:08 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +    @NotNull
Not needed

2022-08-16 13:32 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +    private ResponseWrapper getResponseFromFallbackService(final String url, final Request request) {
We can do sth like this in PartitionedMirrorClient:
    ```
private ResponseWrapper getResponseFromFallbackService(final String initialUrl, final String keyInfo) {
        final String newUrl = this.fallbackService.concat(keyInfo);
        log.info("Host at {} is unavailable. Forwarding the request to {}", initialUrl, newUrl);
        try {
            return this.requestManager.makeRequest(newUrl, true);
        } catch (final IOException fallbackException) {
            throw new MirrorException("Fallback service error", HttpStatus.INTERNAL_SERVER_ERROR,
                fallbackException);
        }
    }
```

2022-08-24 09:49 UTC, raminqaf requested changes

2022-08-24 09:49 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorClient.java
> +        return this.mirrorRequestManager.processResponse(response, this.parser::deserializeList);
In `fetchAll()` we are returning an empty list. Let's return an empty list here as well:
```Java
return Objects.requireNonNullElse(
            this.mirrorRequestManager.processResponse(response, this.parser::deserializeList),
            Collections.emptyList());
```

2022-08-24 09:49 UTC, raminqaf commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +@MicronautTest
You don't need the `@MicronoutTest`

2022-08-24 09:49 UTC, raminqaf commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +class PartitionedMirrorClientTest {
There are a lot of properties here that you can add the `this` to them

2022-08-24 09:49 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
>          } catch (final IOException exception) {
Please consider catching the `IllegalStateException` here

2022-08-24 09:49 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +            throw new IllegalStateException("Partition to MirrorHost mapping is empty.");
Use `MirrorException` instead

2022-08-24 09:49 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +            throw new IllegalStateException(String.format(
Use `MirrorException` instead

2022-08-24 09:49 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManagerWithFallback.java
> +public class MirrorRequestManagerWithFallback implements MirrorRequestManager {
Can you test this class?

2022-08-24 10:06 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/HeaderConstants.java
> +    private static final String UPDATE_PARTITION_HOST_MAPPING_HEADER = "X-Cache-Update";
According to [this](https://stackoverflow.com/questions/3561381/custom-http-headers-naming-conventions) discussion, there is no consensus regarding the naming schema for custom headers. The RFC spec used to recommend the X- naming convention, only to abandon it later. Some developers stick to X-, some use custom names, some say there is no convention, some advise not to use custom headers, etc.
If you don't like it, we can rename it.

2022-08-24 10:53 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/HeaderConstants.java
> +    private static final String UPDATE_PARTITION_HOST_MAPPING_HEADER = "X-Cache-Update";
Okay, nice! Could you please provide a short description of why the X-Cache-Update is set or not set?

2022-08-24 11:04 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManagerWithFallback.java
> +public class MirrorRequestManagerWithFallback implements MirrorRequestManager {
The functionality is tested in `PartitionedMirrorClientTest.shouldReadHeaderAndUpdateRouterWithFewerReplicas`.

2022-08-25 10:13 UTC, raminqaf commented
@DawidNiezgodka, I'll perform an E2E test on this PR and see if the routing works

2022-08-25 13:04 UTC, raminqaf requested changes
Also the `MirrorDataFetcherClient` in the gateway is still using the `DefaultMirrorClient` and not the `PartitionedMirrorClient`.

2022-08-25 13:04 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRegistryClient.java
> +        final MirrorHost mirrorHost = new MirrorHost(topicName, MirrorConfig.directAccess());
You should use the `topicRegistryConfig.getServiceName()` for the `mirrorHost`

2022-08-25 13:04 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRegistryClient.java
> +                                                                      final HttpClient client, final String topicName) {
You don't need the `topicName` here. Since you have the topic registry name in the `TopicRegsitryConfig` object. Please remove it.

2022-08-29 15:17 UTC, raminqaf requested changes

2022-08-29 15:17 UTC, raminqaf commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRegistryClient.java
> +        return new PartitionedMirrorClient<>(mirrorHost, client, Serdes.String(), typeResolver, new DefaultPartitionFinder());
This breaks the TopicRegistry Mirror because you send the request to the TopicRegistry Mirror itself. Concretely, after you initialize the `PartitionedMirrorClient` class you call the `makeRequestForPartitionHostMapping` function in the constructor. This method creates an URL (http://internal-topic-registry/stream/partition) and sends a request, which ends in an internal server error, and the TopicRegistry Mirror fails. Here are also the logs:
```log
INFO com.bakdata.quick.common.api.client.PartitionedMirrorClient - Initializing partition router for the mirror at: internal-topic-registry and the topic: internal-topic-registry.

INFO com.bakdata.quick.common.api.client.MirrorRequestManagerWithFallback - Sending request to: http://internal-topic-registry/streams/partitions
...
INFO com.bakdata.quick.common.api.client.PartitionedMirrorClient - Initializing partition router for the mirror at: internal-topic-registry and the topic: internal-topic-registry. Message: Requested resource responded with status code 500
```
I would suggest that we stick to the `DefaultMirrorClient` for the TopicRegistry and continue to concentrate on the Gateway for the partition routing. Please revert all the changes that involve the TopicRegistry Mirror.

2022-08-30 07:54 UTC, raminqaf commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/QueryListArgumentFetcherTest.java
> +//    }
Please either fix this test or `@Disabled` on this test

2022-09-01 06:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +    private static boolean checkIfCacheMissHeaderSet(final Response response) {
Nit:
```suggestion
    private static boolean isCacheMissHeaderSet(final Response response) {
```

2022-09-01 06:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +        this.responseBody = responseBody;
change to `this(responseBody, false)`

2022-09-01 06:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/HeaderConstants.java
> + * The need arises when a replica of the mirror is added or removed.
This is not really related to the class itself but to its field `UPDATE_PARTITION_HOST_MAPPING_HEADER`

2022-09-01 06:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManager.java
> +     * Submits a request and processes the response. It throws an exception in case of various errors.
> It throws an exception in case of various errors.

Either try to be more specific or remove it, as it currently doesn't really add any insight

2022-09-01 06:15 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManagerWithFallback.java
> +     * If this occurs, we throw an exception. We also set the X-Cache-Update header to a response
```suggestion
     * If this occurs, we throw an exception. We also set the {@link HeaderConstants#X-Cache-Update} header to a response
```
Or something like this

2022-09-01 06:15 UTC, torbsto commented on mirror/src/main/java/com/bakdata/quick/mirror/service/KafkaQueryService.java
> +            .map(response -> Objects.requireNonNull(response.body()).getValue())
Can we really require non null here? Why not filter out empty bodies?

2022-09-02 12:40 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManagerWithFallback.java
> +     * If this occurs, we throw an exception. We also set the X-Cache-Update header to a response
There is no need to expose the constants through getters. You can make them public and remove the `get...`.

2022-09-02 12:53 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/DefaultMirrorRequestManager.java
> +        // as it would have been already closed by the try-with-resources in the callee.
Simplify to something like:
> Don't close response here because its content is read later

2022-09-02 12:53 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManagerWithFallback.java
> +        // The classic try-catch statement and not the try-with-resources is used here because the try-with-resources
see above

2022-09-02 12:53 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorRequestManagerWithFallback.java
> +            throw new MirrorException("Fallback service error", HttpStatus.INTERNAL_SERVER_ERROR,
This is a user-facing error, therefore it should be more meaningful and descriptive. Try to imagine what you would want to know in such a situation and answer those questions. Is there something the user can do? Is it their fault?

2022-09-02 12:53 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/MirrorValueParser.java
> +     * A similar functionality as to the deserialize function but adjusted to work with lists.
If you reference the other function, please link it with `{@link ...}`

2022-09-02 12:53 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/ResponseWrapper.java
> +     * Similar to fromResponse, it creates instances of ResponseWrapper. The difference is
see above; link to method

2022-09-02 12:53 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +    private MirrorClient<String, TopicData> topicDataClient;
Since you've switched back to the DefaultMirrorClient for the registry, maybe it would be better to use a different value type here to avoid confusion. What do you think?

2022-09-02 12:53 UTC, torbsto commented on common/src/test/java/com/bakdata/quick/common/api/client/PartitionedMirrorClientTest.java
> +        // There is no host for partition=3
Why partition 3? Isn't this about partition 2?

```suggestion
        // There is no host for partition=2
```

No?

2022-09-05 10:34 UTC, torbsto approved these changes

2022-09-05 10:34 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +    private final Set<String> distinctHosts;
I think this can be converted to a local variable

2022-09-06 06:46 UTC, raminqaf approved these changes

2022-09-06 10:39 UTC, DawidNiezgodka commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +    private final Set<String> distinctHosts;
`distinctHosts` or `partitionToMirrorHost`? There are both used in more than one place. Generally, IntelliJ is sensitive to variables that could be local and notices you about them. In this case, there is no info about a possible transformation.

2022-09-06 10:49 UTC, torbsto commented on common/src/main/java/com/bakdata/quick/common/api/client/routing/PartitionRouter.java
> +    private final Set<String> distinctHosts;
`distinctHosts` is only used to make the hosts distinct and could be moved to `findDistinctHosts`

2022-09-06 13:20 UTC, merged