Range Query Documentation
bakdata/quick pull request #69
Opened 2022-09-06 14:46 UTC by DawidNiezgodka

Resolves #68.

2022-09-09 07:05 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +fields over which the range is created follow the schema _field**From**_, _field**To**_, where _field_ is the field
I think the naming of the parameters is pure convention, right? So the association with the field is created in the topic directive together with the definition at topic creation. If so, maybe point that out here.

2022-09-09 07:05 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +led to increased sales. With the default fetching strategy in Quick (a so-called Point Query), you could only check
Maybe make clear that this assumes the id as record key

2022-09-09 13:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/index.md
> +- In [Range Queries](range-query.md), you can learn how to use Range Queries, which is a new feature available from
Same goes for point query, and their index equivalents

2022-09-09 13:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +1. It's impossible to define ranges over several fields.
impossible sounds a bit harsh, maybe something like `unsupported`

2022-09-09 13:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/range-query-details.md
> +# Range Queries Details
No semantic line breaks here

2022-09-09 13:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/range-query-details.md
> +This part of the documentation describes the details of processing Range Queries.
I think this goes into too much detail for users. But it would be valuable for developers, so maybe we could move it there

2022-09-09 13:39 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query-details.md
> +# Range Queries Details
```suggestion
# Range query details
```

2022-09-09 13:39 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query-details.md
> +## Kafka State Store
```suggestion
## Kafka state store
```

2022-09-09 13:39 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query-details.md
> +## Range Processor for Range Queries
```suggestion
## Range processor for range queries
```

2022-09-09 13:39 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +# Range Queries
```suggestion
# Range queries
```

2022-09-09 13:39 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +To use Range Queries, you must create a so-called _Range Mirror_.
Just keep in mind that I used the term `Range Mirror` in the design document to make a clear cut between point and range index. But as Torben mentioned there is still the old mirror with range index functionality

2022-09-09 13:39 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +## 2. Define a range in the GraphQL Query type
```suggestion
## 2. Define a range in the GraphQL query type
```

2022-09-13 11:29 UTC, torbsto reviewed
Feedback for the developer docs

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +# Range queries details
Please also apply semantic line breaks to this file

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +For the introduction of range queries, see the following section:
I'd just say `see [Range quereies](...)`

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +[Range queries](https://bakdata.github.io/quick/0.7/user/getting-started/working-with-quick/range-queries/).
I think this way, you can always refer to the current version. Though I mostly use `latest`  if I remember correctly
```suggestion
[Range queries](https://bakdata.github.io/quick/{{ quick_version }}/user/getting-started/working-with-quick/range-queries/).
```

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +By default, it uses RocksDB as an internal key-value cache.
"By default" is not really true, you have to manually set it

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +|      1       | {timestamp: 1, serviceId: 2, requests: 10, success: 8} |
use code blocks here

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +To circumvent the limitation of a key-value store and be able to perform range queries, Quick proposes a new approach
`proposes a new approach` isn't true, since it's probably used elsewhere already

2022-09-13 11:29 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +`<zero_paddings><topicKeyValue>_<zero_paddings><rangeFieldValue>`. <br />
```suggestion
`<zero_paddings><topicKeyValue>_<zero_paddings><rangeFieldValue>`. 
```

2022-09-13 12:15 UTC, DawidNiezgodka commented on docs/docs/developer/range-query-details.md
> +By default, it uses RocksDB as an internal key-value cache.
Hmm, I read [here](https://www.confluent.io/de-de/blog/how-to-tune-rocksdb-kafka-streams-state-stores-performance/) that it is: "_The default state store used in Kafka Streams is RocksDB. Kafka Streams developers initially chose RocksDB because they wanted a write-optimized store. Since RocksDB is the default state store, Kafka Streams provides the means to configure and monitor RocksDB state stores used in a Kafka Streams application._"

2022-09-13 12:34 UTC, torbsto commented on docs/docs/developer/range-query-details.md
> +|      1       | {timestamp: 1, serviceId: 2, requests: 10, success: 8} |
But I'd suggest to render them as code: 
```suggestion
|      `1`       | `{timestamp: 1, serviceId: 2, requests: 10, success: 8}` |
```

2022-09-13 13:33 UTC, DawidNiezgodka commented on docs/docs/developer/range-query-details.md
> +|      1       | {timestamp: 1, serviceId: 2, requests: 10, success: 8} |
ah sry, I thought you were referring to sth else.

2022-09-19 16:12 UTC, raminqaf requested changes

2022-09-19 16:12 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +            "purchaseId" : 456,
The `purchaseId` is a number and does not match the GraphQL schema. Consider using the Purchase type like the previous examples in the documentation.

2022-09-30 16:10 UTC, raminqaf requested changes

2022-09-30 16:10 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +            "purchase" : {
This will not work. Please consider the E2E scenario here:
https://github.com/bakdata/quick/tree/3ca341ed8fd0f391b3f63269c20207443a8d707f/e2e/functional/range

2022-10-04 13:46 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +Let's say you want to find the purchases the client with `userId=123` was unsatisfied with.
```suggestion
Let's say you want to find the purchases the client with `userId=2` was unsatisfied with.
```

2022-10-04 13:46 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +```json title="ratings.json"
Do it like the other `.json` files with `???`.
See the `ingest-data.md` file.

2022-10-04 13:58 UTC, raminqaf requested changes

2022-10-04 15:22 UTC, raminqaf commented on docs/docs/developer/range-query-details.md
> +If it does, the value for the given key is overwritten (precisely as described above).
Maybe point out that if a key has the value null, the key will be deleted from the state store

2022-10-04 15:49 UTC, raminqaf commented on docs/docs/developer/range-query-details.md
> +and [Range Index Process](https://github.com/bakdata/quick/blob/master/mirror/src/main/java/com/bakdata/quick/mirror/range/MirrorRangeProcessor.java).
This is currently main, and it is fine, but this might break the docs if the files get moved or get changed

2022-10-05 09:41 UTC, mkcode92 commented on docs/docs/developer/range-query-details.md
> +1. Modify your GraphQL schema and define a range in the query.
```suggestion

1. Modify your GraphQL schema and define a range in the query.
```
(To display list items in a column)

2022-10-05 09:41 UTC, mkcode92 commented on docs/docs/developer/range-query-details.md
> +`<zero_paddings><topicKeyValue>_<zero_paddings><rangeFieldValue>`.
```suggestion
<nobr>`<zero_paddings><topicKeyValue>_<zero_paddings><rangeFieldValue>`</nobr>.  
```

2022-10-05 09:41 UTC, mkcode92 commented on docs/docs/developer/range-query-details.md
> +(information about the key, the beginning of the range,
```suggestion
(information about the key, the start of the range,
```

2022-10-05 09:41 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/range-query.md
> +    ``` [
```suggestion
    ```
    [
```
plus indent the rest of the snippet. Currently, the code is displayed outside the collapse.

2022-10-05 10:05 UTC, yannick-roeder commented on docs/docs/developer/range-query-details.md
> +a [RangeQueryFetcher](https://github.com/bakdata/quick/blob/c8778ce527575c545a864ccbc3d98e3502fbb2a2/gateway/src/main/java/com/bakdata/quick/gateway/fetcher/RangeQueryFetcher.java).
```suggestion
a [RangeQueryFetcher](https://github.com/bakdata/quick/blob/c8778ce527575c545a864ccbc3d98e3502fbb2a2/gateway/src/main/java/com/bakdata/quick/gateway/fetcher/RangeQueryFetcher.java)
```

2022-10-05 10:08 UTC, yannick-roeder commented on docs/docs/developer/range-query-details.md
> +and [Range Index Process](https://github.com/bakdata/quick/blob/master/mirror/src/main/java/com/bakdata/quick/mirror/range/MirrorRangeProcessor.java).
This should also be called `Range Index Processor` right?
```suggestion
both [Point Index Processor](https://github.com/bakdata/quick/blob/master/mirror/src/main/java/com/bakdata/quick/mirror/MirrorProcessor.java)
and [Range Index Processor](https://github.com/bakdata/quick/blob/master/mirror/src/main/java/com/bakdata/quick/mirror/range/MirrorRangeProcessor.java).
```

2022-10-05 10:14 UTC, yannick-roeder commented on docs/docs/developer/range-query-details.md
> +---
Github renders the whole text as a header because of the `---`. Please make sure this is not a heading on the documentation web page later

2022-10-06 10:01 UTC, raminqaf approved these changes
We'll merge this and later on add the feedback

2022-10-06 10:04 UTC, merged