Removed point/no-point, fixed retention-time - range-field exclusion
bakdata/quick pull request #84
Opened 2022-09-21 13:57 UTC by DawidNiezgodka

Resolves #83 and #73.

2022-09-22 06:04 UTC, raminqaf requested changes
Please update the open API specs and generate them for the PR https://github.com/bakdata/quick-cli/pull/10

2022-09-26 07:24 UTC, raminqaf approved these changes
Looks good. Here the documentation how you can create the client code for the CLI
https://bakdata.github.io/quick/dev/developer/development/#openapi

2022-09-28 09:05 UTC, raminqaf approved these changes

2022-09-28 09:05 UTC, raminqaf commented on manager/src/main/java/com/bakdata/quick/manager/mirror/resources/MirrorResourceLoader.java
> +            throw new BadArgumentException("The --range-field option must not be specified"
Extract the error message in a variable so it does not break in the line.

2022-09-28 09:43 UTC, DawidNiezgodka commented on manager/src/main/java/com/bakdata/quick/manager/mirror/resources/MirrorResourceLoader.java
> +            throw new BadArgumentException("The --range-field option must not be specified"
Done. But is it really that relevant to not break it?

2022-09-28 10:45 UTC, merged