Multisubscription: Docu + Test
bakdata/quick pull request #89
Opened 2022-09-30 11:48 UTC by DawidNiezgodka

Draft PR for #85 and #87.

2022-09-30 12:08 UTC, raminqaf requested changes

2022-09-30 12:08 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +As a reminder, in a single subscription, you add a topic directive
maybe it is good to link the subscription documentation here

2022-09-30 12:08 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +it is recommended to use a GraphQL client, for example, Altair.
Hyperlink Altair

2022-09-30 12:08 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +otherwise, they couldn't be associated) :
Extract to a note box of mkdocs

2022-09-30 12:11 UTC, raminqaf commented
Run `./gradlew checkstyleMain` and resolve the errors

2022-09-30 13:12 UTC, DawidNiezgodka commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/subscription/MultiSubscriptionFetcherTest.java
> +        // Man kännte davon ausgehen, dass F1 avro ist und F2 genauso
The test is not complete yet :)

2022-10-04 11:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +but with a different timestamp and ingest it:
Move the sentence below the code block up, to build an actual sentence

2022-10-04 11:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +This mechanism can be extrapolated to multi-subscriptions
Does that actually work right now?

2022-10-04 11:06 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +An automatic retrieval is done to directly create a response whose elements belong to different types
There are quite a few passive sentences in this paragraph. You can just use `Quick` in those cases, e.g. `Quick does an automatic retrieval to directly create...`

2022-10-04 11:06 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +(see link above). The user-guide section describes
```suggestion
(see link above).
The user-guide section describes
```

2022-10-04 11:06 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +we will adhere to the example from the user-guide
see above; try to avoid 'we'

2022-10-04 11:06 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +(see link above). The user-guide section describes
Please review the following paragraphs as well

2022-10-05 09:30 UTC, yannick-roeder commented on docs/docs/developer/multi-subscription-details.md
> +/user/getting-started/working-with-quick/multi-subscriptions/).
If the file you want to link is in the same repository then you can use a relative link path like this:
```suggestion
[Multi-subscriptions](../user/getting-started/working-with-quick/multi-subscriptions/)
```

2022-10-05 10:56 UTC, mkcode92 commented on docs/docs/developer/multi-subscription-details.md
> +There are three scenarios for building complex objects via multi subscriptions:
separate with newline for rendering list items in a column

2022-10-05 10:56 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +please extend your schema `example.graphql` with the following type:
I would leave out 'please' entirely

2022-10-05 10:56 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +!!! Note
Is that displayed as desired?

2022-10-05 10:56 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +{ "data": {
```suggestion
{
  "data": {
```

2022-10-05 10:56 UTC, mkcode92 commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +1. Modify your schema with and define the multi-subscription.
separate with newline for rendering list items in a column

2022-10-05 11:10 UTC, raminqaf commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +!!! Note
I think the content needs indenting
https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage

2022-10-05 11:11 UTC, raminqaf commented on gradle.properties
> +org.gradle.caching=false
remember to change this later

2022-10-07 09:30 UTC, DawidNiezgodka commented
I would like to handle the problem with the flaky CI/CD in a separate issue.

2022-10-07 09:33 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +the developer [section on multi-subscriptions](https://bakdata.github.io/quick/latest/developer/multi-subscriptions-details/)
Ok, I will handle it in https://github.com/bakdata/quick/issues/93

2022-10-07 14:26 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +This mechanism can be extrapolated to multi-subscriptions
I will check it.

2022-10-07 14:45 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +This mechanism can be extrapolated to multi-subscriptions
Works for three topics :)

2022-10-11 09:56 UTC, raminqaf commented on docs/docs/developer/multi-subscription-details.md
> +```bash
```suggestion
```console
```

2022-10-11 10:10 UTC, torbsto requested changes

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +until it is applied.
I don't get the sentence? Isn't this like saying, the server doesn't know about the request until it is sent? Seems obvious enough to me, that we don't have to mention it in a developer guide.

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +a [MultiSubscriptionFetcher](https://github.com/bakdata/quick/blob/master/gateway/src/main/java/com/bakdata/quick/gateway/fetcher/subscription/MultiSubscriptionFetcher.java)
```suggestion
a [`MultiSubscriptionFetcher`](https://github.com/bakdata/quick/blob/master/gateway/src/main/java/com/bakdata/quick/gateway/fetcher/subscription/MultiSubscriptionFetcher.java)
```

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +Quick constructs a DataFetcherClient (for REST calls)
```suggestion
Quick constructs a `DataFetcherClient` (for REST calls)
```

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +and a SubscriptionProvider (for consuming from a topic)
```suggestion
and a `SubscriptionProvider` (for consuming from a topic)
```

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +To get the missing part of complex objects, the _MultiSubscriptionFetcher_
```suggestion
To get the missing part of complex objects, the `MultiSubscriptionFetcher`
```

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +   but they have not been seen by the _MultiSubscriptionFetcher_ yet
see above; backticks please

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +   i.e., `Click` first, then`Purchase`.
```suggestion
   i.e., `Click` first, then `Purchase`.
```

2022-10-11 10:10 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +
I think this line-break isn't needed

2022-10-11 10:10 UTC, torbsto commented on docs/docs/developer/multi-subscription-details.md
> +If null values are not allowed,
```suggestion
If nullable values are not allowed,
```

2022-10-11 10:49 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +## Modify your schema with and define the multi-subscription
But you first modify (extend) it with a new type, and afterwards you define the subscription. So maybe "extend your schema and define the MS"

2022-10-11 10:49 UTC, torbsto commented on gateway/src/test/java/com/bakdata/quick/gateway/fetcher/subscription/MultiSubscriptionFetcherTest.java
> +    private static GenericRecord newAvroClickStatsOutput(final String id, final long amount) {
I still don't know why you use `newAvro/Proto...Output`  and ` new...Output` here. You can just use the more specific variant, and "downcast" the returned type to its interface.

2022-10-11 10:50 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +## Modify your schema with and define the multi-subscription
But ok, we could move the extension of the schema above - as a preliminary step, and then talk only about the definition of a MS

2022-10-11 10:50 UTC, torbsto commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +## Modify your schema with and define the multi-subscription
I'd say the definition of the multi-subscription includes the modification of the schema

2022-10-11 10:53 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +## Modify your schema with and define the multi-subscription
```suggestion
Before you define the multi-subscription,
add the following type to your schema `schema.gql`:
```graphql
type Click[...]
```
Next, create a topic that holds `Click` entries:
```shell
[...]
```


## Modify your schema with and define the multi-subscription

As a first step, you extend the schema
(from earlier sections of this documentation)
with the definition of a multi-subscription as follows:
```

2022-10-11 12:05 UTC, DawidNiezgodka commented on docs/docs/user/getting-started/working-with-quick/multi-subscriptions.md
> +Please see the [developer section on multi-subscriptions](https://bakdata.github.io/quick/latest/developer/multi-subscriptions-details/),
I think, we can also use relative referencing: `[developer section on multi-subscriptions](../../../developer/multi-subscription-details.md)`

2022-10-13 06:30 UTC, raminqaf commented on common/src/testFixtures/proto/test.proto
> +message ClickStats {
Could you please suffix these with `Proto`? Then we can simplify the imports in the test class

2022-10-13 06:30 UTC, raminqaf commented on common/src/testFixtures/avro/ClickStats.avsc
> +  "name": "ClickStats",
suffix with Avro

2022-10-13 12:01 UTC, raminqaf requested changes

2022-10-13 12:25 UTC, raminqaf approved these changes

2022-10-13 12:46 UTC, merged